MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ModelDir/R-50.pkl"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 256
    USE_LIGHT_HEAD: False
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
DATASETS:
  TRAIN: ("KP180822_quadrotors_train",)  # ("coco_2014_train", "coco_2014_valminusminival")
  TEST: ("KP180822_quadrotors_val",)  # ("coco_2014_minival",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.0025        # 0.0025 * Num-of-GPUs (e.g. 8 GPUs 0.02)
  WEIGHT_DECAY: 0.0001
  STEPS: (6000, 8000)  # (480000, 640000) / Num-of-GPUs (e.g. 8 GPUs (60000, 80000))
  MAX_ITER: 9000        # 720000 / Num-of-GPUs (e.g. 8 GPUs 90000)
  IMS_PER_BATCH: 1       # 2 * Num-of-GPUs (e.g. 8 GPUs 16)
TEST:
  IMS_PER_BATCH: 1
OUTPUT_DIR: /tmp/faster-rcnn-r50-fpn
